source 'https://rubygems.org'

gem 'sinatra'
gem 'sqlite3'
gem 'sequel'
gem 'puma'
gem 'rackup'
gem 'dotenv'
gem 'sinatra-cors'

group :development do
  gem 'shotgun'  # reloads app code so I don't have to restart Sinatra all the time
end

